### ISSUE TITLE
1.17 Modloader Tag 

### ISSUE THREAD

**Issue by YOYOK9** [Focamacho/PigPoop#4]
Hello, this is not a bug per say. Just wanted to let you know you should add the Fabric mod-loader to your 1.17-1.0.0 version on CF. By default mods that do not have mod-loaders set default to Forge. Even though the Fabric api is still listed the mod will show up on the CF app for Forge profiles. 

Just letting you know so before those that don't know or understand the difference between the 2 mod-loaders come and complain "its not working"

**Comment by focamacho** [comment]
Thanks! I totally forgot about changing the tag, thank you for the warning!
